# Generated by Django 5.1.3 on 2024-11-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите описание книги')),
                ('description', models.TextField(verbose_name='Укажите описание к книге')),
                ('price', models.FloatField(verbose_name='Укажите цену')),
                ('start_film', models.DateField(verbose_name='Укажите дату выхода')),
                ('genre', models.CharField(choices=[('Художественный', 'Художественный'), ('Детектив', 'Детектив'), ('Фантастика', 'Фантастика')], max_length=100, verbose_name='Укажите жанр книги')),
                ('mail', models.CharField(max_length=100, verbose_name='Укажите почту автора книги')),
                ('name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('history', models.URLField(verbose_name='Укажите ссылку на историю книги с youtube')),
            ],
        ),
    ]
