# Generated by Django 5.1.3 on 2024-11-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to='film/', verbose_name='Загрузите картину'),
        ),
    ]
