# Generated by Django 5.1.3 on 2024-11-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_books_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='start_film',
        ),
        migrations.AddField(
            model_name='books',
            name='start_book',
            field=models.DateField(null=True, verbose_name='Укажите дату выхода'),
        ),
        migrations.AlterField(
            model_name='books',
            name='history',
            field=models.URLField(null=True, verbose_name='Укажите ссылку на аудио данной книги с youtube'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to='book/', verbose_name='Обложка книги'),
        ),
    ]
