# Generated by Django 5.1.3 on 2024-11-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_books_options_remove_books_start_film_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='history',
            new_name='audio',
        ),
    ]
